name: Express.js CI
on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

#env:
#  POSTGRES_HOST: localhost
#  POSTGRES_PORT: 5432

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "1234567890"
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
            - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.16"

      - name: Installing Dependencies
        run: npm i

      - name: testing our app
        run: npm test